name: Docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-cargo-docs-target-${{ hashFiles('**/Cargo.toml') }}
        path: target
    - name: Build
      run: cargo doc --no-deps
    - name: Upload
      run: |
        yarn add netlify-cli
        ./node_modules/netlify-cli/bin/run deploy --prod --dir=./target/doc
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
